In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objs as go

In [3]:
df = pd.read_csv('final_with_body.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2316 entries, 0 to 2315
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          2316 non-null   int64
 1   Title          2316 non-null   object
 2   DatePublished  2316 non-null   object
 3   Body           2316 non-null   object
 4   vnegative      2316 non-null   float64
 5   vneutral       2316 non-null   float64
 6   vpositive      2316 non-null   float64
 7   compound       2316 non-null   float64
 8   sentiment      2316 non-null   object
 9   fpositive      2316 non-null   float64
 10  fnegative      2316 non-null   float64
 11  fneutral       2316 non-null   float64
 12  score          2316 non-null   float64
 13  label          2316 non-null   object
dtypes: float64(8), int64(1), object(5)
memory usage: 253.4+ KB

In [4]:
df['Body'] = df['Body'].apply(str.lower)
df.head()

,Index,Title,DatePublished,Body,vnegative,vneutral,vpositive,compound,sentiment,fpositive,fnegative,fneutral,score,label
0,0,"SNV, BASF partner to boost small holder farmer...",07-03-2023,four thousand four hundred farmers in east amh...,0.061,0.764,0.175,0.9876,positive,0.753152,0.008772,0.238076,0.753152,positive
1,1,NMC Real Estate hits the ground running,06-26-2023,the new fresh face of the housing development ...,0.013,0.889,0.098,0.9274,positive,0.076639,0.030161,0.893200,0.893200,neutral
2,2,Wild Coffee Ethiopia widens horizon to Kenya,06-26-2023,"wild coffee ethiopia, the top tier coffee bean...",0.000,0.759,0.241,0.9977,positive,0.603660,0.009562,0.386778,0.603660,positive
3,3,IATA calls on Gov’t to clear blocked airline f...,06-26-2023,"the global trade association of airlines, inte...",0.059,0.729,0.212,0.9973,positive,0.656810,0.237762,0.105428,0.656810,positive
4,4,Promoting equipment maintenance at the DMP,06-26-2023,doraleh multipurpose port (dmp) and china merc...,0.000,0.784,0.216,0.9963,positive,0.887694,0.007952,0.104354,0.887694,positive

In [8]:
def search(sstr):
    searched_df = df[df['Body'].str.contains(sstr.lower())]
    df_aspects = pd.read_csv('aspects.csv')
    df_positive = searched_df[searched_df['label']=='positive']
    df_negative = searched_df[searched_df['label']=='negative']
    df_neutral = searched_df[searched_df['label']=='neutral']
    new = {'aspect':sstr, 'positive':len(df_positive), 'negative':len(df_negative), 'neutral':len(df_neutral)}
    df_toappend = pd.DataFrame(data=new, index=[1])
    df_aspects= pd.concat([df_aspects, df_toappend], ignore_index=True)
    df_aspects.to_csv('aspects.csv', index=False)

In [9]:
search('Education')
search('Health')
search('Industry')
search('Employment')
search('Economy')
search('Tourism')
search('Climate')
search('Infrastructure')
search('Law')